### NumPy First Steps

### Programming for Data Science
### Last Updated: Jan 15, 2023
---  

### PREREQUISITES
- import
- functions
- for ... in

### SOURCES 
- **Python for Data Analysis, Chapter 4 (be sure to read this)**
- https://numpy.org/
- https://en.wikipedia.org/wiki/NumPy
- https://www.scipy.org/
- https://en.wikipedia.org/wiki/SciPy
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
- https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

### OBJECTIVES
- Take your first steps with numpy
 


### CONCEPTS

- The numpy package contains useful functions for math operations
- The ndarray is the workhorse of the package


---

### numpy

In this lesson we will explore the python package *numpy*.  
This package is super powerful. 

Our focus will be on:
- importing and calling some random number generating functions
- illustrating operations on ndarrays
- learning how to subset ndarrays

### Motivation

I need a random number! I heard numpy can do that!  

In [3]:
import numpy as np
np.random.randint(1,7)

6

Learn what this function does:

In [4]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
     

Include the size parameter to generate 10 random integers in [1, 6]

In [6]:
np.random.randint(1,7,10)
# the third number indicates how many numbers are expected to be generated.

array([1, 6, 4, 2, 6, 1, 2, 5, 3, 4])

---

### The ndarray in Numpy

Details [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

Represents a multidimensional, homogeneous array of fixed-size items. 

Uses very efficient operations

Arrays should be constructed using `array()`, `zeros()` or `empty()`.

### NumPy ndarray Operations


Create an array with some data

In [7]:
x = np.array(([2,3,1],[3,1,2]))
x

array([[2, 3, 1],
       [3, 1, 2]])

Get the shape of the data (rows, columns)

In [8]:
print(x.shape)

(2, 3)


In [9]:
# generate matrix of random normals 

x = np.random.randn(2, 3)
x

array([[-0.72274883,  0.37247207, -0.23342149],
       [-0.06904385,  0.37036524, -0.35001145]])

In [10]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)

    Return a sample (or samples) from the "standard normal" distribution.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned

Scale the matrix - notice how this operates elementwise

In [11]:
x * 2

array([[-1.44549767,  0.74494415, -0.46684297],
       [-0.13808769,  0.74073049, -0.70002289]])

Addition

In [12]:
x + x

array([[-1.44549767,  0.74494415, -0.46684297],
       [-0.13808769,  0.74073049, -0.70002289]])

Reciprocal

In [13]:
1 / x

array([[ -1.38360652,   2.68476504,  -4.28409577],
       [-14.48355006,   2.70003738,  -2.85704942]])

#### Creating Matrices with Special Structure - can create arrays of zeros, ones, and identity matrices

In [14]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [15]:
x.shape

(5,)

In [16]:
y=np.zeros([5,1])

In [17]:
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [18]:
y.shape

(5, 1)

In [19]:
z=np.zeros([1,5])
print(z)

[[0. 0. 0. 0. 0.]]


In [20]:
z.shape

(1, 5)

In [21]:
q=np.zeros((2,3))
print(q)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
q.shape

(2, 3)

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Indexing and Slicing

In [25]:
z = np.random.randn(5)
z

array([ 0.44144192, -0.48261415,  1.15017729,  0.56587718, -0.30641212])

In [26]:
# select from start to one before end
z[1:4]

array([-0.48261415,  1.15017729,  0.56587718])

In [27]:
# does this make sense?
z[1:-1]

array([-0.48261415,  1.15017729,  0.56587718])

In [28]:
# boolean indexing
z[z>0.15]

array([0.44144192, 1.15017729, 0.56587718])

In [29]:
# assignment
z[1] = 3
z

array([ 0.44144192,  3.        ,  1.15017729,  0.56587718, -0.30641212])

In [30]:
# 2D
w = np.random.randn(3,3)
w

array([[-1.2203953 ,  0.53463557, -1.09463167],
       [ 1.16735461, -1.84093899, -0.29161345],
       [ 0.70199411, -0.3301732 ,  0.47349289]])

In [34]:
w[1:] # the first number indicates rows wanted, and the seconde one indicates columns wanted.

array([[ 1.16735461, -1.84093899, -0.29161345],
       [ 0.70199411, -0.3301732 ,  0.47349289]])

In [35]:
# subset rows and columns
w[1:, :2]

array([[ 1.16735461, -1.84093899],
       [ 0.70199411, -0.3301732 ]])

#### TRY FOR YOURSELF
Write code to generate a new array *w2* that starts with *w* and sets all negative values to 0.
Then print *w2* and *w*.  

Be sure to use:  
w2 = w.copy()  
or w will get updated as well

In [38]:
w2 = w.copy()
w2[w2 < 0] = 0

In [39]:
w2 = w.copy()
w2[w2 < 0] = 0
print('w2:\n', w2)
print('')
print('w:\n', w)

w2:
 [[0.         0.53463557 0.        ]
 [1.16735461 0.         0.        ]
 [0.70199411 0.         0.47349289]]

w:
 [[-1.2203953   0.53463557 -1.09463167]
 [ 1.16735461 -1.84093899 -0.29161345]
 [ 0.70199411 -0.3301732   0.47349289]]


---  

#### Next Steps

This notebook provided some information to get you started.

To learn more, please refer to your textbook and the links in the Sources section at top.